Matplotlib warning
awslabs/syne-tune pull request #408
Opened 2022-10-31 13:29 UTC by Valavanca

*Issue #251*

*Description of changes:*
The warning has been corrected because the metric label is explicitly indicated; Display all metrics in an experiment relative to time.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-10-31 21:56 UTC, wistuba requested changes

2022-10-31 21:56 UTC, wistuba commented on syne_tune/experiments.py
> +                    if self.metric_mode() == "max"
As far as I understand the code, `self.metric_mode()` returns the mode for the first metric. Plots for all metrics with a different mode than the first one, will be plotted incorrectly. I think the user is able to provide as many metrics as she wants but does not necessarily need to provide the corresponding modes. Therefore, I'm not sure we can actually plot all metrics.

2022-11-01 10:06 UTC, Valavanca commented on syne_tune/experiments.py
> +                    if self.metric_mode() == "max"
Сlear. I also found several similar cases in the source code when only a first metric and a singular mode are used. 
For the sake of simplification and consistency, I simply removed the legend call.

2022-11-01 11:31 UTC, wistuba approved these changes
Thanks a lot for your contribution.

2022-11-01 11:33 UTC, merged