Fix issue with yahpo uploading/syncing with S3
awslabs/syne-tune pull request #419
Opened 2022-11-10 08:30 UTC by geoalgo

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-11-10 09:02 UTC, wistuba requested changes
It's not fully addressing the issue. Generation of the benchmark is still not happening.

2022-11-10 10:26 UTC, geoalgo commented
> It's not fully addressing the issue. Generation of the benchmark is still not happening.

Could you be more specific? 

It is generating the benchmark in my case and is currently fixing an issue (local files were incorrectly checked for yahpo).

2022-11-10 16:49 UTC, wistuba commented
When creating the issue, `generate()` was not triggered. I don't see how these changes will account for that. If you delete files from S3 and locally, does it recreate it correctly?

2022-11-11 08:24 UTC, wistuba commented
For `load_blackbox("yahpo-rbv2_xgboost")` I get following exception:

```FileNotFoundError: [Errno 2] No such file or directory: '~/.blackbox-repository/yahpo/rbv2_xgboost/encoding.json'```

2022-11-16 13:13 UTC, geoalgo commented
@wistuba it should work now, the logic with paths had to be updated to support sub directories on s3 (which is needed for yahpo).

2022-11-17 08:28 UTC, wistuba commented on syne_tune/blackbox_repository/repository.py
> +    print(f"tgt folder {tgt_folder}")
remove

2022-11-17 08:28 UTC, wistuba commented on syne_tune/blackbox_repository/repository.py
> +            print(f"s3_folder {s3_folder}")
remove

2022-11-17 08:41 UTC, geoalgo commented on syne_tune/blackbox_repository/repository.py
> +    print(f"tgt folder {tgt_folder}")
Ok, done.

2022-11-17 08:45 UTC, wistuba approved these changes

2022-11-17 10:48 UTC, merged