Change SearcherWithRandomSeed to StochasticSearcher
awslabs/syne-tune pull request #552
Opened 2023-02-15 08:50 UTC by aaronkl

*Description of changes:*

Changes SearcherWithRandomSeed to StochasticSearcher to highlight that any randomized algorithm - algorithms that make randomized decisions internally - should derive from this class. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-02-16 11:28 UTC, mseeger requested changes
Could you also please grep all the docs and do the replacement there as well?

2023-02-16 11:28 UTC, mseeger commented on syne_tune/optimizer/schedulers/searchers/__init__.py
>      SearcherWithRandomSeedAndFilterDuplicates,
Could also rename this to `StochasticAndFilterDuplicatesSearcher`

2023-02-20 11:02 UTC, mseeger approved these changes
But let us merge this only once the new release is out, to be safe

2023-02-20 11:14 UTC, wesk commented
Also, would you please update the title of this PR to follow the conventionalcommits convention guidelines as described here: https://github.com/awslabs/syne-tune/blob/main/CONTRIBUTING.md#contributing-via-pull-requests

And also yes, please wait to merge until after this release

2023-02-22 13:26 UTC, merged