feature: Remote metrics
awslabs/syne-tune pull request #590
Opened 2023-03-09 10:12 UTC by mseeger

Closes #563 .

----

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-03-09 10:14 UTC, mseeger commented on docs/source/tutorials/benchmarking/bm_local.rst
> +     --experiment_tag tutorial-local --benchmark resnet_cifar10 \
Fix: Must not contain "_"

2023-03-15 09:05 UTC, jgolebiowski requested changes
Looks very good overall. I have a small refactor request to avoid any confusion down the line.

2023-03-15 10:45 UTC, mseeger commented on benchmarking/commons/launch_remote_local.py
> +    callback.register_metrics_with_estimator(estimator)
You are right, I was taking a shortcut here

2023-03-15 10:50 UTC, mseeger commented on syne_tune/remote/remote_metrics_callback.py
> +        logger.info(f"Remote tuning metrics reported: {self.metric_names}")
Done.

2023-03-15 10:59 UTC, jgolebiowski approved these changes

2023-03-15 10:59 UTC, jgolebiowski commented
LGTM! Thats a very cool change.

2023-03-15 11:02 UTC, mseeger commented
Giovanni asked for it. It would be better if we had a nice configuration for the CloudWatch dashboard that we could either ask the customer to adjust or (even better) we could auto-adjust as part of calling the training job

2023-03-15 11:02 UTC, merged