Fix: Random seed initialisation in scheduler_searcher.py.
awslabs/syne-tune pull request #644
Opened 2023-05-02 14:27 UTC by sighellan

Similar to #608 .

int32 is limited to 2**31-1. On windows this was resulting in a program crash when running `scheduler = BORE(conf_space, metric, random_seed=None)`. The problem did not occur when specifying the `random_seed`.

```
File c:\[...]\syne_tune\optimizer\schedulers\scheduler_searcher.py:45, in TrialSchedulerWithSearcher.__init__(self, config_space, **kwargs)
     43 random_seed = kwargs.get("random_seed")
     44 if random_seed is None:
---> 45     random_seed = np.random.randint(0, 2**32)
     46 logger.info(f"Master random_seed = {random_seed}")
     47 self.random_seed_generator = RandomSeedGenerator(random_seed)

File mtrand.pyx:746, in numpy.random.mtrand.RandomState.randint()

File _bounded_integers.pyx:1336, in numpy.random._bounded_integers._rand_int32()

ValueError: high is out of bounds for int32
```

----

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-05-02 16:17 UTC, mseeger requested changes

2023-05-02 16:17 UTC, mseeger commented on syne_tune/optimizer/schedulers/scheduler_searcher.py
> +            random_seed = np.random.randint(0, 2**31 - 1)
Thanks!

I'd actually prefer to have a function like this in `syne_tune/optimizer/random_seeds.py`:

```
def generate_random_seed(random_state=np.random) -> int:
   return random_state.randint(0, 2**31 - 1)
```

Then, use this to implement both `RandomSeedGenerator.__call__` and sample the master random seed elsewhere.

2023-05-02 16:17 UTC, mseeger commented on syne_tune/optimizer/schedulers/scheduler_searcher.py
> +            random_seed = np.random.randint(0, 2**31 - 1)
Then, we have the logic in one place.

2023-05-02 16:27 UTC, mseeger commented on syne_tune/optimizer/schedulers/scheduler_searcher.py
> +            random_seed = np.random.randint(0, 2**31 - 1)
I've also submitted #645 with some further fixes along these lines.

2023-05-02 17:45 UTC, mseeger commented
The CI is failing, because the commit message should start with "fix:". It currently starts with "Fix:"

2023-05-02 18:59 UTC, wesk commented
Validation is failing because your commit title does not have the `fix: ` prefix. The way the validation currently behaves is that at least one commit must have a valid ConventionalCommits prefix (in addition to the PR title). To fix this, you can either 1) push a new commit with a valid prefix to your branch, or 2) amend and force-push the commit to your branch. 

Or, option 3), if we merge https://github.com/awslabs/syne-tune/pull/646 first, then we should be able to merge your PR as-is

2023-05-02 19:15 UTC, mseeger commented
@sighellan I could also do the fix in #646 and we close this one. Up to you.

2023-05-03 09:57 UTC, mseeger commented
Thanks @sighellan for this catch! I am providing a fix in #645 , which also cleans things up a bit, so this won't happen again.

2023-05-03 09:57 UTC, closed without merging

2023-05-03 13:15 UTC, sighellan commented
Sounds good! I agree that #645  is a neater fix.