fix: Remote launcher must not pass extra params to hpo_main
awslabs/syne-tune pull request #680
Opened 2023-05-17 11:50 UTC by mseeger

----

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-05-19 07:18 UTC, wesk commented
Rather than creating this new `skip_initial_jobs` parameter, an alternative would be to make the command safe to retry. For example, in a 5-job experiment, if jobs 1, 3, 4, 5 all succeed but job 2 fails, the command should be smart enough so that if we re-invoke the experiment, we can re-launch just job 2.

This would be useful because not all jobs fail immediately with a sync error, some failures may be async, for example due to server errors.

2023-05-19 08:48 UTC, wesk requested changes
To quickly fix remote launching in main, we reverted https://github.com/awslabs/syne-tune/pull/662. We can circle-back to determine the best way to add this feature and then open a new `feat:` PR.

2023-05-22 16:12 UTC, mseeger commented
OK, we need to decide whether we want to allow launch_remote.py to have additional args which are not passed down to hpo_main.py, or not.

If yes, and we don't want the solution I put in (which is ugly), we need a better one (@jgolebiowski ?). If no, this is OK for the short term, but I feel this is going to come back. Take the mechanism of Jacek to try again when launching a job failed due to service quota exceeded. You want to configure that one, but that option not be passed down.

2023-05-22 20:33 UTC, mseeger commented
OK, #688 is doing what #662 was supposed to do, without introducing issues. Can close this one here.

2023-05-22 20:33 UTC, closed without merging